// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace TrussBridge
{
    public class TrussBridgeOutputs: ResultsBase
    {
		/// <summary>
		/// The length of the bridge.
		/// </summary>
		[JsonProperty("Bridge Length")]
		public double BridgeLength {get;}

		/// <summary>
		/// The total length of steel.
		/// </summary>
		[JsonProperty("Total Steel Length")]
		public double TotalSteelLength {get;}



        /// <summary>
        /// Construct a TrussBridgeOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public TrussBridgeOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a TrussBridgeOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public TrussBridgeOutputs(double bridgeLength, double totalSteelLength): base()
        {
			this.BridgeLength = bridgeLength;
			this.TotalSteelLength = totalSteelLength;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}