// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace TrussBridge
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class TrussBridgeInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public TrussBridgeInputs(Line @path, double @width, double @height, double @endElevation, IList<Vector3> @abutmentLocations, Overrides @overrides, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<TrussBridgeInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @path, @width, @height, @endElevation, @abutmentLocations, @overrides});
            }
        
            this.Path = @path;
            this.Width = @width;
            this.Height = @height;
            this.EndElevation = @endElevation;
            this.AbutmentLocations = @abutmentLocations;
            this.Overrides = @overrides;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>The path of the center line of the bridge.</summary>
        [Newtonsoft.Json.JsonProperty("Path", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Line Path { get; set; }
    
        /// <summary>The width of the bridge.</summary>
        [Newtonsoft.Json.JsonProperty("Width", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Width { get; set; } = 3D;
    
        /// <summary>The height of the bridge.</summary>
        [Newtonsoft.Json.JsonProperty("Height", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Height { get; set; } = 2.5D;
    
        /// <summary>The elevation of the bridge at its end</summary>
        [Newtonsoft.Json.JsonProperty("End Elevation", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double EndElevation { get; set; } = 0D;
    
        /// <summary>Approximate locations of abutments.</summary>
        [Newtonsoft.Json.JsonProperty("Abutment Locations", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Vector3> AbutmentLocations { get; set; }
    
        [Newtonsoft.Json.JsonProperty("overrides", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Overrides Overrides { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public partial class Overrides 
    
    {
        [Newtonsoft.Json.JsonConstructor]
        public Overrides(IList<ProfileOverride> @profile)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<Overrides>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @profile});
            }
        
            this.Profile = @profile;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Profile", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<ProfileOverride> Profile { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public partial class ProfileOverride 
    
    {
        [Newtonsoft.Json.JsonConstructor]
        public ProfileOverride(ProfileIdentity @identity, ProfileValue @value)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<ProfileOverride>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @identity, @value});
            }
        
            this.Identity = @identity;
            this.Value = @value;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Identity", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ProfileIdentity Identity { get; set; }
    
        [Newtonsoft.Json.JsonProperty("Value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public ProfileValue Value { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public partial class ProfileIdentity 
    
    {
        [Newtonsoft.Json.JsonConstructor]
        public ProfileIdentity(Line @curve)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<ProfileIdentity>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @curve});
            }
        
            this.Curve = @curve;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Curve", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Line Curve { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public partial class ProfileValue 
    
    {
        [Newtonsoft.Json.JsonConstructor]
        public ProfileValue(ProfileValueProfileName @profileName)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<ProfileValue>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @profileName});
            }
        
            this.ProfileName = @profileName;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("ProfileName", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ProfileValueProfileName ProfileName { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public enum ProfileValueProfileName
    {
        [System.Runtime.Serialization.EnumMember(Value = @"W44x335")]
        W44x335 = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W44x290")]
        W44x290 = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W44x285")]
        W44x285 = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W44x262")]
        W44x262 = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W44x248")]
        W44x248 = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W44x230")]
        W44x230 = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W44X224")]
        W44X224 = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W44x198")]
        W44x198 = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x655")]
        W40x655 = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x593")]
        W40x593 = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x531")]
        W40x531 = 10,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x503")]
        W40x503 = 11,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x480")]
        W40x480 = 12,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x466")]
        W40x466 = 13,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x436")]
        W40x436 = 14,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x431")]
        W40x431 = 15,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x397")]
        W40x397 = 16,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x392")]
        W40x392 = 17,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x372")]
        W40x372 = 18,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x362")]
        W40x362 = 19,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x331")]
        W40x331 = 20,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x328")]
        W40x328 = 21,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x327")]
        W40x327 = 22,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x324")]
        W40x324 = 23,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x321")]
        W40x321 = 24,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x298")]
        W40x298 = 25,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x297")]
        W40x297 = 26,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x278")]
        W40x278 = 27,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x277")]
        W40x277 = 28,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x268")]
        W40x268 = 29,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x264")]
        W40x264 = 30,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x249")]
        W40x249 = 31,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x244")]
        W40x244 = 32,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x235")]
        W40x235 = 33,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x221")]
        W40x221 = 34,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x215")]
        W40x215 = 35,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x211")]
        W40x211 = 36,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x199")]
        W40x199 = 37,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x192")]
        W40x192 = 38,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x183")]
        W40x183 = 39,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x174")]
        W40x174 = 40,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x167")]
        W40x167 = 41,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W40x149")]
        W40x149 = 42,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x848")]
        W36x848 = 43,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x798")]
        W36x798 = 44,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x720")]
        W36x720 = 45,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x650")]
        W36x650 = 46,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x588")]
        W36x588 = 47,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x527")]
        W36x527 = 48,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x485")]
        W36x485 = 49,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x439")]
        W36x439 = 50,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x393")]
        W36x393 = 51,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x359")]
        W36x359 = 52,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x328")]
        W36x328 = 53,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x300")]
        W36x300 = 54,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x280")]
        W36x280 = 55,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x260")]
        W36x260 = 56,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x256")]
        W36x256 = 57,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x245")]
        W36x245 = 58,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x232")]
        W36x232 = 59,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x230")]
        W36x230 = 60,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x210")]
        W36x210 = 61,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x194")]
        W36x194 = 62,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x182")]
        W36x182 = 63,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x170")]
        W36x170 = 64,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x160")]
        W36x160 = 65,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x150")]
        W36x150 = 66,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W36x135")]
        W36x135 = 67,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x619")]
        W33x619 = 68,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x567")]
        W33x567 = 69,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x515")]
        W33x515 = 70,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x468")]
        W33x468 = 71,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x424")]
        W33x424 = 72,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x387")]
        W33x387 = 73,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x354")]
        W33x354 = 74,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x318")]
        W33x318 = 75,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x291")]
        W33x291 = 76,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x263")]
        W33x263 = 77,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x241")]
        W33x241 = 78,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x221")]
        W33x221 = 79,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x201")]
        W33x201 = 80,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x169")]
        W33x169 = 81,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x152")]
        W33x152 = 82,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x141")]
        W33x141 = 83,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x130")]
        W33x130 = 84,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W33x118")]
        W33x118 = 85,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x581")]
        W30x581 = 86,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x526")]
        W30x526 = 87,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x477")]
        W30x477 = 88,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x433")]
        W30x433 = 89,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x391")]
        W30x391 = 90,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x357")]
        W30x357 = 91,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x326")]
        W30x326 = 92,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x292")]
        W30x292 = 93,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x261")]
        W30x261 = 94,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x235")]
        W30x235 = 95,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x211")]
        W30x211 = 96,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x191")]
        W30x191 = 97,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x173")]
        W30x173 = 98,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x148")]
        W30x148 = 99,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x132")]
        W30x132 = 100,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x124")]
        W30x124 = 101,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x116")]
        W30x116 = 102,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x108")]
        W30x108 = 103,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x99")]
        W30x99 = 104,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W30x90")]
        W30x90 = 105,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x539")]
        W27x539 = 106,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x494")]
        W27x494 = 107,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x448")]
        W27x448 = 108,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x407")]
        W27x407 = 109,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x368")]
        W27x368 = 110,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x336")]
        W27x336 = 111,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x307")]
        W27x307 = 112,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x281")]
        W27x281 = 113,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x258")]
        W27x258 = 114,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x235")]
        W27x235 = 115,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x217")]
        W27x217 = 116,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x194")]
        W27x194 = 117,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x178")]
        W27x178 = 118,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x161")]
        W27x161 = 119,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x146")]
        W27x146 = 120,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x129")]
        W27x129 = 121,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x114")]
        W27x114 = 122,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x102")]
        W27x102 = 123,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x94")]
        W27x94 = 124,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W27x84")]
        W27x84 = 125,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x492")]
        W24x492 = 126,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x450")]
        W24x450 = 127,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x408")]
        W24x408 = 128,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x370")]
        W24x370 = 129,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x335")]
        W24x335 = 130,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x306")]
        W24x306 = 131,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x279")]
        W24x279 = 132,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x250")]
        W24x250 = 133,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x229")]
        W24x229 = 134,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x207")]
        W24x207 = 135,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x192")]
        W24x192 = 136,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x176")]
        W24x176 = 137,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x162")]
        W24x162 = 138,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x146")]
        W24x146 = 139,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x131")]
        W24x131 = 140,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x117")]
        W24x117 = 141,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x104")]
        W24x104 = 142,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x103")]
        W24x103 = 143,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x94")]
        W24x94 = 144,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x84")]
        W24x84 = 145,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x76")]
        W24x76 = 146,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x68")]
        W24x68 = 147,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x62")]
        W24x62 = 148,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W24x55")]
        W24x55 = 149,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x402")]
        W21x402 = 150,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x364")]
        W21x364 = 151,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x333")]
        W21x333 = 152,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x300")]
        W21x300 = 153,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x275")]
        W21x275 = 154,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x248")]
        W21x248 = 155,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x223")]
        W21x223 = 156,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x201")]
        W21x201 = 157,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x182")]
        W21x182 = 158,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x166")]
        W21x166 = 159,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x147")]
        W21x147 = 160,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x132")]
        W21x132 = 161,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x122")]
        W21x122 = 162,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x111")]
        W21x111 = 163,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x101")]
        W21x101 = 164,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x93")]
        W21x93 = 165,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x83")]
        W21x83 = 166,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x73")]
        W21x73 = 167,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x68")]
        W21x68 = 168,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x62")]
        W21x62 = 169,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x57")]
        W21x57 = 170,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x55")]
        W21x55 = 171,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x50")]
        W21x50 = 172,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x48")]
        W21x48 = 173,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W21x44")]
        W21x44 = 174,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x311")]
        W18x311 = 175,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x283")]
        W18x283 = 176,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x258")]
        W18x258 = 177,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x234")]
        W18x234 = 178,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x211")]
        W18x211 = 179,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x192")]
        W18x192 = 180,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x175")]
        W18x175 = 181,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x158")]
        W18x158 = 182,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x143")]
        W18x143 = 183,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x130")]
        W18x130 = 184,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x119")]
        W18x119 = 185,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x106")]
        W18x106 = 186,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x97")]
        W18x97 = 187,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x86")]
        W18x86 = 188,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x76")]
        W18x76 = 189,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x71")]
        W18x71 = 190,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x65")]
        W18x65 = 191,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x60")]
        W18x60 = 192,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x55")]
        W18x55 = 193,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x50")]
        W18x50 = 194,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x46")]
        W18x46 = 195,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x40")]
        W18x40 = 196,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W18x35")]
        W18x35 = 197,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x100")]
        W16x100 = 198,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x89")]
        W16x89 = 199,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x77")]
        W16x77 = 200,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x67")]
        W16x67 = 201,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x57")]
        W16x57 = 202,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x50")]
        W16x50 = 203,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x45")]
        W16x45 = 204,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x40")]
        W16x40 = 205,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x36")]
        W16x36 = 206,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x31")]
        W16x31 = 207,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W16x26")]
        W16x26 = 208,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x808")]
        W14x808 = 209,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x730")]
        W14x730 = 210,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x665")]
        W14x665 = 211,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x605")]
        W14x605 = 212,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x550")]
        W14x550 = 213,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x500")]
        W14x500 = 214,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x455")]
        W14x455 = 215,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x426")]
        W14x426 = 216,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x398")]
        W14x398 = 217,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x370")]
        W14x370 = 218,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x342")]
        W14x342 = 219,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x311")]
        W14x311 = 220,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x283")]
        W14x283 = 221,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x257")]
        W14x257 = 222,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x233")]
        W14x233 = 223,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x211")]
        W14x211 = 224,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x193")]
        W14x193 = 225,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x176")]
        W14x176 = 226,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x159")]
        W14x159 = 227,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x145")]
        W14x145 = 228,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x132")]
        W14x132 = 229,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x120")]
        W14x120 = 230,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x109")]
        W14x109 = 231,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x99")]
        W14x99 = 232,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x90")]
        W14x90 = 233,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x82")]
        W14x82 = 234,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x74")]
        W14x74 = 235,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x68")]
        W14x68 = 236,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x61")]
        W14x61 = 237,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x53")]
        W14x53 = 238,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x48")]
        W14x48 = 239,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x43")]
        W14x43 = 240,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x38")]
        W14x38 = 241,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x34")]
        W14x34 = 242,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x30")]
        W14x30 = 243,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x26")]
        W14x26 = 244,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W14x22")]
        W14x22 = 245,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x336")]
        W12x336 = 246,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x305")]
        W12x305 = 247,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x279")]
        W12x279 = 248,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x252")]
        W12x252 = 249,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x230")]
        W12x230 = 250,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x210")]
        W12x210 = 251,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x190")]
        W12x190 = 252,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x170")]
        W12x170 = 253,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x152")]
        W12x152 = 254,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x136")]
        W12x136 = 255,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x120")]
        W12x120 = 256,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x106")]
        W12x106 = 257,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x96")]
        W12x96 = 258,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x87")]
        W12x87 = 259,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x79")]
        W12x79 = 260,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x72")]
        W12x72 = 261,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x65")]
        W12x65 = 262,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x58")]
        W12x58 = 263,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x53")]
        W12x53 = 264,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x50")]
        W12x50 = 265,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x45")]
        W12x45 = 266,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x40")]
        W12x40 = 267,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x35")]
        W12x35 = 268,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x30")]
        W12x30 = 269,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x26")]
        W12x26 = 270,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x22")]
        W12x22 = 271,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x19")]
        W12x19 = 272,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x16")]
        W12x16 = 273,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W12x14")]
        W12x14 = 274,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x112")]
        W10x112 = 275,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x100")]
        W10x100 = 276,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x88")]
        W10x88 = 277,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x77")]
        W10x77 = 278,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x68")]
        W10x68 = 279,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x60")]
        W10x60 = 280,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x54")]
        W10x54 = 281,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x49")]
        W10x49 = 282,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x45")]
        W10x45 = 283,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x39")]
        W10x39 = 284,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x33")]
        W10x33 = 285,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x30")]
        W10x30 = 286,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x26")]
        W10x26 = 287,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x22")]
        W10x22 = 288,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x19")]
        W10x19 = 289,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x17")]
        W10x17 = 290,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x15")]
        W10x15 = 291,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W10x12")]
        W10x12 = 292,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x67")]
        W8x67 = 293,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x58")]
        W8x58 = 294,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x48")]
        W8x48 = 295,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x40")]
        W8x40 = 296,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x35")]
        W8x35 = 297,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x31")]
        W8x31 = 298,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x28")]
        W8x28 = 299,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x24")]
        W8x24 = 300,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x21")]
        W8x21 = 301,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x18")]
        W8x18 = 302,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x15")]
        W8x15 = 303,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x13")]
        W8x13 = 304,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W8x10")]
        W8x10 = 305,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W6x25")]
        W6x25 = 306,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W6x20")]
        W6x20 = 307,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W6x16")]
        W6x16 = 308,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W6x15")]
        W6x15 = 309,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W6x12")]
        W6x12 = 310,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W6x9")]
        W6x9 = 311,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W6x8_5")]
        W6x8_5 = 312,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W5x19")]
        W5x19 = 313,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W5x16")]
        W5x16 = 314,
    
        [System.Runtime.Serialization.EnumMember(Value = @"W4x13")]
        W4x13 = 315,
    
    }
}